In [1]:
import urllib.request

def read_tsv(link):

    headers = {
            "User-Agent": (
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                "(KHTML, like Gecko) Chrome/126.0 Safari/537.36"
            )
        }
    try:
        req = urllib.request.Request(link, headers=headers)
        with urllib.request.urlopen(req, timeout=30) as resp:
            text = resp.read()
            return text.decode("utf-8")
    except:
        print( "Not good" )

def format_data(data):
    # data = data.decode("utf-8")
    data = data.split("\n")
    data = [[n.replace("\r", "") for n in i.split("\t")] for i in data]
    return data

In [2]:
PUBLISH_LINK = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTximK54RzevgtA54SwKnbA7P8o_d_nPcaqr0VG1jh7q3bbkOQSgesrUoeALTWujpycf-AtXO-eXFxU/pub?output=tsv"

data = read_tsv( PUBLISH_LINK )
data

'\t\t\t\t\t\tMILESTONE\t\t\t\tActivity Narrative for each FFY\tIs this a habitat project?\tDoes this include education or community events?\tFFY\tSECURED FUNDS (internal)\t\t\t\t\t\t\t\tANTICIPATED FUNDS\t\t\t\t2025-2035 ACTION AGENDA LANGUAGE (DO NOT EDIT)\t\t\t\t\t\tCWA Core Program(s) the project supports: \r\nGoal\tObjective Code\tObjective Desc\tSubtitle\tAction Code\tAction Desc\tActivities-Deliverables\tStatus\tRevised Milestone?\tLead Implementers\t\t\t\t\tSection 320 (contractual or subawards)\tSection 320  (Staff Costs -starting FY27)\tIIJA  (contractual or subawards)\tIIJA  (Staff Costs)\tHRF-match  (contractual or subawards)\tHRF-match  (Staff Costs)\tLeveraged/Match (Partner-directed)\tNarrative\tHEP Staff Lead\tNarrative for New Intiatives/Projects/Deliverables and Prospective Sources of New Funding \tTotal Amount (requested)\tFFY  (Anticipated Start Date)\tLong Text\tKey Partners\tResources\tIndicators\tCommitments\tCross Cutting Goals\t\r\nWater Quality\tA\tExtreme Weather\tMaximize clean water and other benefits through integrated adaptation approaches\t1\tAdvance watershed plans and/or pilot projects that aim to reduce flood risk and improve water quality\tIdentification of critical watersheds where multiple projects under the LTCPs, MS4, existing watershed improvement plans, and resiliency efforts will impact water quality and ability to address water resources and other concerns.\tNot started\tNo\tHEP\tHEP will work with partners to support watershed plans and/or pilot project efforts that engage local communities through technical assistance programs, technology transfers, and grants to support integrated adaptation measures.  Such measures include green stormwater infrastructure, natural and nature-based features, cloudburst technologies, and other resiliency strategies that achieve multiple benefits in keeping with federal and state hazard mitigation programs.  A specific effort will be to identify how such project planning can also help meet permit requirements under the Clean Water Act.  This work will help ensure that hazard mitigation projects, such as the efforts being considered under the USACE Harbor and Tributaries Study or other state and local planning efforts, fully assess implications of their construction on water quality issues.  This work may focus on one or more priority watersheds as identified by HEP and partners in New York and New Jersey. An RFP will be released to support between 4 and 6 projects that align with this action with completion of efforts by June 2028.  Deliverable(s): RFP for FY 24 and FY 25/26 IIJA funding. Grants management and other support of monitoring/data collection, planning, workforce training, and/or community engagement activities that will advance resiliency and build community capacity.  \tNo\tNo\t2024, 2025, 2026, 2027, 2028\t\t$69,098\t$350,000.00\t\t\t\t\t\t\t\t\t\tAdvancing a holistic approach to stormwater management, coastal flooding, and clean water is crucial for success in the face of recurring extreme weather. Communities throughout the Estuary are increasingly experiencing both coastal and inland flooding due to persistent extreme wet weather events. The aftermath of these events has been devastating for many communities. At the same time, changing precipitation patterns have resulted in increased combined sewer overflows (CSOs) and non-point source pollution.  HEP will collaborate with partners to clarify the risks in critical shorelines and watersheds. This will include identifying or elevating existing management and regulatory solutions, upland best management practices, storm surge barriers, and other solutions underway that will mitigate flooding. HEP will work with partners to support watershed plans and/or pilot project efforts that engage local communities through technical assistance programs, technology transfers, and grants to support integrated adaptation measures. Such measures include green stormwater infrastructure, natural and nature-based features, cloudburst technologies, and other resiliency strategies that achieve multiple benefits. A specific target will be identifying how such watershed planning can help meet permit requirements under the Clean Water Act.\tUSEPA, USACE, USGS, NOAA, NYSDEC, HREP, NJDEP, NYCDEP, NGOs and CBOs in pilot watersheds.\t$$$ - staff time plus grants between $50-250k\tPathogens, Dissolved Oxygen, Total Suspended Solids, Salinity, pH, Water Temperature, Riparian Area Integrity\tExtreme Weather, Access for All,  Co-benefits, Partnerships & Leveraging\t- Habitat - Public Access - Port & Maritime - Community Engagement\t(2) identifying polluted waters and developing plans to restore them  (total maximum daily loads) (6) protecting coastal waters through the National Estuary Program (7) protecting large aquatic ecosystems\r\n\t\t\t\t\t\tAdvance management and regulatory solutions in select watersheds in partnership with state and local government and community partners.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tIntegrated watershed plans and/or pilot projects that support permit requirements.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tSharing opportunities for peer learning, funding, and training.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t2\tSupport the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features\tGrants to support community maintenance of green stormwater infrastructure and natural and nature-based solutions.\tIn progress\tNo\tHEP\tHEP will provide funding and technical assistance to support green infrastructure community engagement, stewardship, and/or workforce training. This work will seek to support LTCPs, stormwater management, address flooding, and improve water quality through the IIJA funding and seek to build on lessons learned from Perth Amboy, Newark, NYC DEP, RAIN Coalition, and the Jamaica Bay-Rockaway Parks Conservancy.  A possible focus will be working in port communities in Newark, Elizabeth, New York City, New York’s Capital District, or elsewhere to advance this work (PM-D-1).  Deliverable (s): RFP for GI in one or more community stewardship effort \t\t\t2026, 2027\t\t$37,712\t\t$19,028.29\t\t\t\t\t\t\t\t\tNew York and New Jersey are leaders in advancing integrated approaches that incorporate nature-based solutions alongside traditional grey infrastructure to improve water quality, enhance habitat, and build more resilient communities. As agencies, municipalities and utilities continue to invest millions to improve water infrastructure and resiliency, it is essential to maintain green assets to ensure they provide sustained benefits. This initiative also presents an opportunity to expand the green workforce and engage local community organizations and residents in their community’s resilience efforts. Stewardship organizations, utilities, and municipal governments have started investing time and funding to develop local pipelines for this work. However, despite these efforts, finding  the necessary funds for both maintenance and workforce development remains a challenge for the region.  HEP will collaborate with partners to address these challenges and advance opportunities to build and deploy the workforce and innovative tools required to maintain nature-based water quality and resiliency projects.\tNYSDEC, NJDEP, NYCDEP, NJHDG, NY and NJ local government, NYCSWCD, NGO’s including RAIN Coalition, Riverkeeper, JBRPC, Groundwork Hudson Valley, Newark DIG, JWW, and NYC SWIM.\t$$$$ - staff time plus grants between $250k-1M\tPathogens, Dissolved Oxygen, Nitrogen, Phosphorus, Total Suspended Solids, Area of tidal wetlands, Percent & Distribution of Natural Shorelines, Riparian Area Integrity\tExtreme Weather, Access for All, Co-benefits, Partnerships & Leveraging\t- Habitat - Community Engagement\t(4) addressing diffuse, nonpoint sources of pollution (6) protecting coastal waters through the National Estuary Program\r\n\t\t\t\t\t\tFinal engineering design and construction specification documents for six right-of-way bioswale bumpouts in the City of Perth Amboy, NJ\tCompleted\tN/A\tRutgers Cooperative Extension Water Resources Program, City of Perth Amboy\tA green infrastructure grant was awarded to the Rutgers Cooperative Extension Water Resources Program and the City of Perth Amboy to provide technical assistance and complete the final design and construction specifications for six right-of-way bioswale bumpouts, three of which were determined as a priority by the City of Perth Amboy which inlucde Cornell and Neville Streets; Cornell and Lawrie Street; and Jefferson and Maple Street. These sites were identified from a green infrastructure plan previously funded by HEP and led by the Rutgers Cooperative Extension Water Resources Program. With assistance from Rutgers and the IIJA funds, the City of Perth Amboy applied and were awarded a $438,512 Stormwater Assistance Grant from NJDEP to implement the three bioswales. The project was completed by June 2025.\tYes\tNo\t2022, 2023\t\t\t$48,000.00\t\t\t\t$483,512.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tSupport education and outreach of green infrastructure throughout the City of Newark, NJ\tCompleted\tN/A\tNewarkDIG\tA green infrastructure grant was awarded to Newark DIG to support outreach and education across the city. They delivered 224 doorknockers in each ward of the City of Newark through mult-day canvassing, including infoming residents about green infrastructure project installation occuring at Clinton-Badger Avenue. In addition, funds were used to support their GI Reformers who participated in 8 community events, and installed a sign for the City’s first-led green infrastructure project at Clinton-Badger Avenue. The also supported over 80 storm drains that were cleaned and track over the course of the project and engaged over 50 youth and student volunteers to steward those drains (September 2025).\tNo\tYes\t2022, 2023, 2024, 2025\t\t\t$77,000.00\t\t\t\t$1,076,660.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tFinal engineering designs for three green infrastructure projects in Newark, NJ \tCompleted\tN/A\tNewarkDIG, Rutgers Cooperative Extension Water Resources Program\tNewark DIG in partnership with Rutgers Cooperative Extension Water Rescources Program identified three projects in their green infrastructure plan to move from initial concept to full design. The selected sites included: Sussex Avenue School, Quitman Avenue School, and South Street School (July 2025).\tNo\tNo\t2022, 2023, 2024, 2025\t\t\t$0.00\t\t\t\t$0.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tSupport the advacement of local residents and organizations to in workforce development for green infrastructure and nature-based solutions\tCompleted\tN/A\tNewarkDIG\tNewark DIG successfully developed a curriculum for advanced GI training to 4 certified National Green Infrastructure Certification Program graduates who have engaged in hands-on rain garden construction and design in Paterson, Newark, and Perth Amboy (December 2024). In the Fall of 2025, NewarkDIG released annoucement offering stipends for residents interested in being trained under the National Green Infrastructure Certification Program. Over 250 responses were received for the limited cohort seat of 25 people. Of the 25 selected applicants, 15 advanced the training but only 9 fully completed the course and were allowed to take the final exam for certification (February 2026).\tNo\tYes\t2024, 2025, 2026\t\t\t$25,000.00\t\t\t\t$0.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tAdvance a GI project under the Harlem River Watershed Management Plan\tIn progress\tN/A\tHEP, UWFP, NYC Parks, TreeBed LLC\tHEP and BxH UWFP will work with NYC Parks and community partners to advance GI priorities of the Harlem River Watershed Management Plan. This initiative includes multiple projects that will enhance greening and stormwater management in the Harlem River watershed, beginning with tree plantings, a feasibility study for stormwater management and erosion reduction in two NYC Parks, and stewardship training (PA-C-1).\tYes\tYes\t2026, 2027\t\t\t$50,000.00\t\t\t\t$50,000.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tIdentify funding opportunities and work with partners to apply for nature-based solutions maintenance and workforce development.\tCompleted\tNo\tHEP, RAIN Coalition\tRAIN Coalition developed a training model to prepare workers and collaborated with the DOE Fund to apply and was awarded NYCDEP’s RFP for right-of-way GI maintenance across East New York and Ozone Park. Coalition members maintained 67 assets throughout the grant period: 53 NYCDEP right-of-way rain gardens, 11 Parks’ rain gardens, 1 NYCDEP street end, and 1 Parks’ Greenstreet, in the Bronx, Gowanus and Newtown watersheds (May 2025).\tNo\tNo\t2022, 2023, 2024\t\t\t$100,000.00\t\t\t\t$75,000.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tElevate models and/or monitoring protocols for community maintenance.\tCompleted\tNo\tRAIN Coalition\tRAIN Coalition were successful in developing a shared project plan and budget to coordinate a community-centered workforce pipeline to include maintenance of 146,053 square feet of GI, 900 street trees, and 41.2 acres of wetlands and forested natural areas, and engage 105 participants in paid transitional employment, 585 participants in paid training and green career exposure, and 22,050 participants in 1,000 educational tours and events.\tNo\tNo\t2022, 2023, 2024\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tTrain young adults in wetland and nature-based solutions maintenance\tCompleted\tN/A\tJamaica Bay-Rockaway Parks Conservancy\tJamaica Bay-Rockaway Parks Conservancy successfully hired 12 wetland fellows and provided 612+ hours of training, including WEDG certification and career readiness workshops. Fellows removed 10,000 lbs of marine debris, hosted 26 public clean ups, 12 community programs, and launched Rockaway Refresh – a weekly post-weekend cleanup initiative. 4 of the fellows secured full-time positions, 2 with NYC Parks and 2 with NYS Parks, and the Assistant Supervisor secured a full-time position with NYS Parks.\tYes\tNo\t2024, 2025\t\t\t$50,000.00\t\t\t\t$205,000.00\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tRestore and maintain a rain garden in Paterson, NJ piloting a maintenance plan for the Board of Education\tCompleted\tN/A\tPassaic River Coalition\tPassaic River Coalition restored and maintained the John F. Kenedy High School rain garden with educators and students (June 2025). The restoration of the rain garden included additional plantings and weeding to develop an all-season rain garden. A maintenance plan was also developed with the Paterson School Grounds staff for long term maintenance of school rain gardens.\tYes\tYes\t2022, 2023, 2024\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tProvide technical assistance and support to coalitions focused on nature-based solutions, its maintenance, and workforce development such as Jersey Water Works, NYC SWIM Coalition, and Sewage Free-Streets and Rivers.\tIn progress\tNo\tHEP, JWW, NYC SWIM, SFSR\tSteering Committee member of Jersey Water Works (2016) and the Hudson River Watershed Monitoring Collaborative (2024). Active member of the NYC SWIM Coalition (2018) and technical advisor to Sewage Free Streets and Rivers (2018). \tNo\tNo\t2025, 2026, 2027\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\tPublished "So You\'re a Green Infrastructure Champion, Now What? A Roadmap for Project Planning and Advocacy" (https://cms.jerseywaterworks.org/wp-content/uploads/2024/07/NJF_JWWMGIOutreach_V2.pdf)\tCompleted\tN/A\tHEP, JWW\tAs the co-chair of the Jersey Water Works\' Green Infrastructure Committee. the co-chairs contributed to Jersey Water Works\' publication, "So You\'re a Green Infrastructure Champion, Now What? A Roadmap for Project Planning and Advocacy", published in July 2024. The document was used during the JerseyWater Works Annual Conference to engage members and active Green Infrastructure Champions to support the stewardship of green infrastructure in communities across the state of New Jersey as it relates to the Municipal Separate Storm Sewer System (MS4) permit.\tNo\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t3\tAdvance the use of water resource data and decision-making tools by local government\tTrain government staff and community members on the use of available tools in pilot locations.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTechnological advancements have led to the creation of various tools that can help communities and municipalities understand their risks from extreme weather events, inland and coastal flooding, and urban heat island effects. In addition, there are a number of water quality data collection efforts that can be used to support or inform these available tools and inform management decisions. But these tools and data are not widely utilized by municipalities or their communities.  HEP will seek to improve municipal and community use of available tools and data developed by federal and state agencies including NOAA, USACE, EPA, and NYSDEC and NJDEP.\tNJDEP, NYSDEC, HREP, NJHDG, NYCDEP, Rutgers, Riverkeeper, NGOs and CBOs\t$$$ - staff time plus grants between $50k-$250 K\tPathogens, Dissolved Oxygen, pH, Water Temperature, Water Level\tExtreme Weather, Access for All, Actionable Science & Data, Partnership & Leveraging\t- Habitat - Public Access - Community Engagement\t(1) establishing water quality standards (2) identifying polluted waters and developing plans to restore them  (total maximum daily loads) (3) permitting discharges of pollutants from point sources  (National Pollutant Discharge Elimination System permit) (4) addressing diffuse, nonpoint sources of pollution (5) protecting wetlands (6) protecting coastal waters through the National Estuary Program (7) protecting large aquatic ecosystems\r\n\t\t\t\t\t\tSupport a community of practice around data analysis, visualization, and communication.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t4\tCommunicate the impacts extreme weather will have on our aging infrastructure and public health\tWater stories and/or water quality fact sheets to highlight infrastructure improvement projects and the benefits expected.\t\tNo\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tLong Term Control Plans (LTCPs) and the advancement of Municipal Separate Storm Sewer System (MS4) permits across the Estuary have prompted municipalities and utilities to invest billions in upgrading aging infrastructure. Often underground and unseen, these critical improvements include upgrades to pipelines, pump stations, culverts, and wastewater treatment plants. This infrastructure is also vulnerable to extreme weather  including sea level rise, increased precipitation and rising water tables. As projects progress under LTCP and MS4 permits as well as resiliency measures, a gap exists in how communities understand the importance of this work, its costs, and its relation to public health and ecological concerns.  HEP will collaborate with partners to better illustrate the health of the Estuary, its impact on our daily lives, and how proposed capital improvements benefit the Estuary. HEP will build on its State of the Estuary Report and develop water quality fact sheets for select regional waterbodies and/or sub watersheds. HEP will generate and share water stories to connect capital improvement projects and resilience measures to estuarine health. A possible focus will be the Enclosed and Confined Waterbodies identified in the HRE CRP.  HEP will also work closely with its technical work groups and committees to elevate areas where future conditions can make a significant impact.\tUSEPA, USGS, NYSDEC, NJDEP, NYCDEP, NJHDG, CBOs and local government partner(s)\t$$$ - staff time plus grants between $50k-$250 K\tPathogens, Dissolved Oxygen, Water Tem

In [3]:
import pandas as pd
def make_df(data_list):
    formatted_data = format_data(data_list)
    formatted_data = formatted_data[1:] #skip the first line because of the double headers
    columns = formatted_data[0]
    print( columns )
    df = pd.DataFrame( data = formatted_data[1:], columns = columns )
    df = df.replace("", None )
    # Filter to only necessary columns
    df = df[['Goal','Objective Code','Objective Desc','Subtitle','Action Code','Action Desc','Activities-Deliverables','Status','Lead Implementers']]

    return df

df = make_df( data )
df.head()

['Goal', 'Objective Code', 'Objective Desc', 'Subtitle', 'Action Code', 'Action Desc', 'Activities-Deliverables', 'Status', 'Revised Milestone?', 'Lead Implementers', '', '', '', '', 'Section 320 (contractual or subawards)', 'Section 320  (Staff Costs -starting FY27)', 'IIJA  (contractual or subawards)', 'IIJA  (Staff Costs)', 'HRF-match  (contractual or subawards)', 'HRF-match  (Staff Costs)', 'Leveraged/Match (Partner-directed)', 'Narrative', 'HEP Staff Lead', 'Narrative for New Intiatives/Projects/Deliverables and Prospective Sources of New Funding ', 'Total Amount (requested)', 'FFY  (Anticipated Start Date)', 'Long Text', 'Key Partners', 'Resources', 'Indicators', 'Commitments', 'Cross Cutting Goals', '']

,Goal,Objective Code,Objective Desc,Subtitle,Action Code,Action Desc,Activities-Deliverables,Status,Lead Implementers
0,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,1,Advance watershed plans and/or pilot projects ...,Identification of critical watersheds where mu...,Not started,HEP
1,NaN,NaN,NaN,NaN,NaN,NaN,Advance management and regulatory solutions in...,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,Integrated watershed plans and/or pilot projec...,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,"Sharing opportunities for peer learning, fundi...",NaN,NaN
4,NaN,NaN,NaN,NaN,2,Support the management and maintenance of gree...,Grants to support community maintenance of gre...,In progress,HEP

In [4]:
cols_tofill = ['Goal','Objective Code','Objective Desc','Subtitle','Action Code','Action Desc']

for c in cols_tofill:
    df[c] = df[c].ffill()
    df[c] = df[c].str.strip()

df.head()

,Goal,Objective Code,Objective Desc,Subtitle,Action Code,Action Desc,Activities-Deliverables,Status,Lead Implementers
0,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,1,Advance watershed plans and/or pilot projects ...,Identification of critical watersheds where mu...,Not started,HEP
1,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,1,Advance watershed plans and/or pilot projects ...,Advance management and regulatory solutions in...,NaN,NaN
2,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,1,Advance watershed plans and/or pilot projects ...,Integrated watershed plans and/or pilot projec...,NaN,NaN
3,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,1,Advance watershed plans and/or pilot projects ...,"Sharing opportunities for peer learning, fundi...",NaN,NaN
4,Water Quality,A,Extreme Weather,Maximize clean water and other benefits throug...,2,Support the management and maintenance of gree...,Grants to support community maintenance of gre...,In progress,HEP

In [8]:
gr = df.set_index(cols_tofill)
gr.head()

                                                                                                                                                                                          Activities-Deliverables  \
Goal          Objective Code Objective Desc  Subtitle                                           Action Code Action Desc
Water Quality A              Extreme Weather Maximize clean water and other benefits through... 1           Advance watershed plans and/or pilot projects t...  Identification of critical watersheds where mu...
                                                                                                            Advance watershed plans and/or pilot projects t...  Advance management and regulatory solutions in...
                                                                                                            Advance watershed plans and/or pilot projects t...  Integrated watershed plans and/or pilot projec...
                                                                                                            Advance watershed plans and/or pilot projects t...  Sharing opportunities for peer learning, fundi...
                                                                                                2           Support the management and maintenance of green...  Grants to support community maintenance of gre...

                                                                                                                                                                     Status  \
Goal          Objective Code Objective Desc  Subtitle                                           Action Code Action Desc
Water Quality A              Extreme Weather Maximize clean water and other benefits through... 1           Advance watershed plans and/or pilot projects t...  Not started
                                                                                                            Advance watershed plans and/or pilot projects t...          NaN
                                                                                                            Advance watershed plans and/or pilot projects t...          NaN
                                                                                                            Advance watershed plans and/or pilot projects t...          NaN
                                                                                                2           Support the management and maintenance of green...  In progress

                                                                                                                                                               Lead Implementers
Goal          Objective Code Objective Desc  Subtitle                                           Action Code Action Desc
Water Quality A              Extreme Weather Maximize clean water and other benefits through... 1           Advance watershed plans and/or pilot projects t...               HEP
                                                                                                            Advance watershed plans and/or pilot projects t...               NaN
                                                                                                            Advance watershed plans and/or pilot projects t...               NaN
                                                                                                            Advance watershed plans and/or pilot projects t...               NaN
                                                                                                2           Support the management and maintenance of green...               HEP

In [ ]:
df_dict = df.to_dict('records')

[{'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '1',
  'Action Desc': 'Advance watershed plans and/or pilot projects that aim to reduce flood risk and improve water quality',
  'Activities-Deliverables': 'Identification of critical watersheds where multiple projects under the LTCPs, MS4, existing watershed improvement plans, and resiliency efforts will impact water quality and ability to address water resources and other concerns.',
  'Status': 'Not started',
  'Lead Implementers': 'HEP'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '1',
  'Action Desc': 'Advance watershed plans and/or pilot projects that aim to reduce flood risk and improve water quality',
  'Activities-Deliverables': 'Advance management and regulatory solutions in select watersheds in partnership with state and local government and community partners.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '1',
  'Action Desc': 'Advance watershed plans and/or pilot projects that aim to reduce flood risk and improve water quality',
  'Activities-Deliverables': 'Integrated watershed plans and/or pilot projects that support permit requirements.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '1',
  'Action Desc': 'Advance watershed plans and/or pilot projects that aim to reduce flood risk and improve water quality',
  'Activities-Deliverables': 'Sharing opportunities for peer learning, funding, and training.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Grants to support community maintenance of green stormwater infrastructure and natural and nature-based solutions.',
  'Status': 'In progress',
  'Lead Implementers': 'HEP'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Final engineering design and construction specification documents for six right-of-way bioswale bumpouts in the City of Perth Amboy, NJ',
  'Status': 'Completed',
  'Lead Implementers': 'Rutgers Cooperative Extension Water Resources Program, City of Perth Amboy'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Support education and outreach of green infrastructure throughout the City of Newark, NJ',
  'Status': 'Completed',
  'Lead Implementers': 'NewarkDIG'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Final engineering designs for three green infrastructure projects in Newark, NJ ',
  'Status': 'Completed',
  'Lead Implementers': 'NewarkDIG, Rutgers Cooperative Extension Water Resources Program'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Support the advacement of local residents and organizations to in workforce development for green infrastructure and nature-based solutions',
  'Status': 'Completed',
  'Lead Implementers': 'NewarkDIG'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Advance a GI project under the Harlem River Watershed Management Plan',
  'Status': 'In progress',
  'Lead Implementers': 'HEP, UWFP, NYC Parks, TreeBed LLC'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Identify funding opportunities and work with partners to apply for nature-based solutions maintenance and workforce development.',
  'Status': 'Completed',
  'Lead Implementers': 'HEP, RAIN Coalition'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Elevate models and/or monitoring protocols for community maintenance.',
  'Status': 'Completed',
  'Lead Implementers': 'RAIN Coalition'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Train young adults in wetland and nature-based solutions maintenance',
  'Status': 'Completed',
  'Lead Implementers': 'Jamaica Bay-Rockaway Parks Conservancy'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Restore and maintain a rain garden in Paterson, NJ piloting a maintenance plan for the Board of Education',
  'Status': 'Completed',
  'Lead Implementers': 'Passaic River Coalition'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Provide technical assistance and support to coalitions focused on nature-based solutions, its maintenance, and workforce development such as Jersey Water Works, NYC SWIM Coalition, and Sewage Free-Streets and Rivers.',
  'Status': 'In progress',
  'Lead Implementers': 'HEP, JWW, NYC SWIM, SFSR'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '2',
  'Action Desc': 'Support the management and maintenance of green stormwater infrastructure and natural and nature-based resiliency features',
  'Activities-Deliverables': 'Published "So You\'re a Green Infrastructure Champion, Now What? A Roadmap for Project Planning and Advocacy" (https://cms.jerseywaterworks.org/wp-content/uploads/2024/07/NJF_JWWMGIOutreach_V2.pdf)',
  'Status': 'Completed',
  'Lead Implementers': 'HEP, JWW'},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '3',
  'Action Desc': 'Advance the use of water resource data and decision-making tools by local government',
  'Activities-Deliverables': 'Train government staff and community members on the use of available tools in pilot locations.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '3',
  'Action Desc': 'Advance the use of water resource data and decision-making tools by local government',
  'Activities-Deliverables': 'Support a community of practice around data analysis, visualization, and communication.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '4',
  'Action Desc': 'Communicate the impacts extreme weather will have on our aging infrastructure and public health',
  'Activities-Deliverables': 'Water stories and/or water quality fact sheets to highlight infrastructure improvement projects and the benefits expected.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'A',
  'Objective Desc': 'Extreme Weather',
  'Subtitle': 'Maximize clean water and other benefits through integrated adaptation approaches',
  'Action Code': '4',
  'Action Desc': 'Communicate the impacts extreme weather will have on our aging infrastructure and public health',
  'Activities-Deliverables': 'Elevate projects and policies that will make significant impacts to the resiliency of the Estuary.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Sustain and disseminate baseline data from HRECOS.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Advance and support regional and/or pilot efforts to monitor key waterways, including water quality monitoring in the Hudson River Ecosystem Monitoring Program.',
  'Status': 'In progress',
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Support the transition phase of the Community Water Quality Testing Program ',
  'Status': 'In progress',
  'Lead Implementers': 'HEP, NYC SWIM Coalition, Community Water Quality Testing Program'},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Advancing quality assurance and quality control',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Protocols and/or SOPs, including lab certification, accessible to community scientists and volunteer monitoring programs.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '1',
  'Action Desc': 'Support water quality monitoring programs and sharing of data in prioritized areas, such as public access sites or areas with known data gaps',
  'Activities-Deliverables': 'Community of practice around data analysis, visualization, and communication.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '2',
  'Action Desc': 'Advance debris prevention efforts through improved monitoring, debris removal, and innovative solutions',
  'Activities-Deliverables': 'Advance the 2021-2026 Mid-Atlantic Marine Debris Action Plan and participate in workshops.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'B',
  'Objective Desc': 'Advance Monitoring',
  'Subtitle': 'Support water quality monitoring and holistic assessments of water quality to prioritize actions and policies',
  'Action Code': '2',
  'Action Desc': 'Advance debris prevention efforts through improved monitoring, debris removal, and innovative solutions',
  'Activities-Deliverables': 'Collaborate with partners to advance decisions on technologies, research, and / or grant opportunities.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'C',
  'Objective Desc': 'Shared Standards',
  'Subtitle': 'Sustain ongoing dialogue across agency and state boundaries to ensure progress and clarify end goals for shared waters',
  'Action Code': '1',
  'Action Desc': 'Improve coordination and communication amongst regulatory agencies, permittees, local government, and the public on current science and design conditions in shared waters',
  'Activities-Deliverables': 'WQWG and other meetings to share information and help build consensus on UAA and other tools.',
  'Status': 'In progress',
  'Lead Implementers': 'HEP WQWG '},
 {'Goal': 'Water Quality',
  'Objective Code': 'C',
  'Objective Desc': 'Shared Standards',
  'Subtitle': 'Sustain ongoing dialogue across agency and state boundaries to ensure progress and clarify end goals for shared waters',
  'Action Code': '1',
  'Action Desc': 'Improve coordination and communication amongst regulatory agencies, permittees, local government, and the public on current science and design conditions in shared waters',
  'Activities-Deliverables': 'Hosted a series of webinars for "Frontiers on Monitoring, Modeling, and Management" to advance UAAs, LTCPs, MS4 and other permit requirements',
  'Status': 'Completed',
  'Lead Implementers': 'WQWG'},
 {'Goal': 'Water Quality',
  'Objective Code': 'C',
  'Objective Desc': 'Shared Standards',
  'Subtitle': 'Sustain ongoing dialogue across agency and state boundaries to ensure progress and clarify end goals for shared waters',
  'Action Code': '1',
  'Action Desc': 'Improve coordination and communication amongst regulatory agencies, permittees, local government, and the public on current science and design conditions in shared waters',
  'Activities-Deliverables': 'Public engagement tools and techniques to aid the states and local government  in understanding uses.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'C',
  'Objective Desc': 'Shared Standards',
  'Subtitle': 'Sustain ongoing dialogue across agency and state boundaries to ensure progress and clarify end goals for shared waters',
  'Action Code': '1',
  'Action Desc': 'Improve coordination and communication amongst regulatory agencies, permittees, local government, and the public on current science and design conditions in shared waters',
  'Activities-Deliverables': 'Implement updates to a CSO Notification System that improves public information on public access sites in the Harbor Estuary',
  'Status': 'Blocked',
  'Lead Implementers': 'HEP, WQWG, NJHDG, PVSC, NYCDEP'},
 {'Goal': 'Water Quality',
  'Objective Code': 'D',
  'Objective Desc': 'Emerging Contaminants',
  'Subtitle': 'Improve understanding of the fate, transport, and ecosystem impact of known and emerging contaminants in the Harbor Estuary',
  'Action Code': '1',
  'Action Desc': 'Support and share research to help assess the potential impact of chemicals of emerging concern',
  'Activities-Deliverables': 'Workshops, seminars, and/or RFPs to identify need on one or more topics. ',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Water Quality',
  'Objective Code': 'D',
  'Objective Desc': 'Emerging Contaminants',
  'Subtitle': 'Improve understanding of the fate, transport, and ecosystem impact of known and emerging contaminants in the Harbor Estuary',
  'Action Code': '1',
  'Action Desc': 'Support and share research to help assess the potential impact of chemicals of emerging concern',
  'Activities-Deliverables': 'Research and scientific report(s) on specific topics.',
  'Status': nan,
  'Lead Implementers': nan},
 {'Goal': 'Habitat and Ecological Health',
  'Objective Code': 'A',
  'Objective Desc': 'Target Characteristics',
  'Subtitle': 'Progress on key target ecosystem characteristic goals of the Hudson Raritan Estuary Comprehensive Restoration Plan',
  'Action Code': '1',
  'Action Desc': 'Conserve habitat and secure restoration sites through acquisition',
  'Activities-Deliverables': 'Report on conservation status of HRE CRP sites.',
  'Status': 'In progress',
  'Lead Implementers': nan},
 {'Goal': 'Habitat and Ecological Health',
  'Objective Code': 'A',